
/* Generated by fzmparser version 2.2 --- DO NOT EDIT! */

/* Uses following resources: */
/* [6 events, 2+0 states, 1 inputs, 2 outputs, 3 match regs, 2 capture regs] */

#include "sct_fsm.h"


void sct_fsm_init (void)
{
LPC_SCT->CONFIG = (LPC_SCT->CONFIG & ~0x00060001) | 0x00000001; /* UNIFIED */

/* MATCH/CAPTURE registers */

/* Unified counter - register side L is used and accessed as 32 bit value, reg H is not used */
LPC_SCT->REGMODE_L = 0x00000018;         /* U: 3x MATCH, 2x CAPTURE, 0 unused */

LPC_SCT->MATCH[0].U = val_match_max_width;             /* match_max_width */
LPC_SCT->MATCHREL[0].U = val_match_max_width;
LPC_SCT->MATCH[1].U = val_match_min_width;             /* match_min_width */
LPC_SCT->MATCHREL[1].U = val_match_min_width;
LPC_SCT->MATCH[2].U = val_match_no_input;             /* match_no_input */
LPC_SCT->MATCHREL[2].U = val_match_no_input;
LPC_SCT->CAPCTRL[3].U = 0x00000002;
LPC_SCT->CAPCTRL[4].U = 0x00000028;

/* OUTPUT registers */
LPC_SCT->OUT[0].SET = 0x00000002;        /* timeout */
LPC_SCT->OUT[0].CLR = 0x00000001;
LPC_SCT->OUT[1].SET = 0x00000008;        /* width_error */
LPC_SCT->OUT[1].CLR = 0x00000021;
  /* Unused outputs must not be affected by any event */
LPC_SCT->OUT[2].SET = 0;
LPC_SCT->OUT[2].CLR = 0;
LPC_SCT->OUT[3].SET = 0;
LPC_SCT->OUT[3].CLR = 0;
LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000000) | 0x00000003;

/* Conflict resolution register */

/* EVENT registers */
LPC_SCT->EVENT[0].CTRL = 0x00001002;     /* U: */
LPC_SCT->EVENT[0].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[1].CTRL = 0x00002400;     /* U: */
LPC_SCT->EVENT[1].STATE = 0xFFFFFFFF;
LPC_SCT->EVENT[5].CTRL = 0x00006800;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[5].STATE = 0x00000001;
LPC_SCT->EVENT[2].CTRL = 0x0000D001;     /* U: --> state state_1 */
LPC_SCT->EVENT[2].STATE = 0x00000001;
LPC_SCT->EVENT[3].CTRL = 0x00006800;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[3].STATE = 0x00000002;
LPC_SCT->EVENT[4].CTRL = 0x00005000;     /* U: --> state U_ENTRY */
LPC_SCT->EVENT[4].STATE = 0x00000002;

/* STATE registers */
LPC_SCT->STATE_L = 0;

/* state names assignment: */
  /* State U 0: U_ENTRY */
  /* State U 1: state_1 */

/* CORE registers */
LPC_SCT->START_L = 0x00000000;
LPC_SCT->STOP_L =  0x00000000;
LPC_SCT->HALT_L =  0x00000000;
LPC_SCT->LIMIT_L = 0x00000003;
LPC_SCT->EVEN =    0x00000021;

}
